
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db # Важно: 'db' - это имя сервиса БД в Docker Compose
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

volumes:
  db_data:
